language: erlang

otp_release:
  - 23.3.1
  - 22.3.4
  - 21.3.8.1
  - 20.3.8

branches:
  only:
    - master

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

script: "make travis"
