on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests on ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.1']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3.17.0
      - name: Common Test tests
        run: rebar3 ct --sname ct
      - name: Dialyzer
        run: rebar3 dialyzer
